
FROM eclipse-temurin:17-alpine AS build


RUN apk add --no-cache maven curl


WORKDIR /app


COPY pom.xml .
RUN mvn dependency:go-offline


COPY . .
RUN mvn clean package -DskipTests


FROM eclipse-temurin:17-alpine

WORKDIR /app


COPY --from=build /app/target/syspa_be-0.0.1-SNAPSHOT.jar app.jar


EXPOSE 8058

CMD ["java", "-jar", "app.jar", "--server.address=0.0.0.0", "--server.port=${PORT:-8058}"]
